version: '3'
tasks:
  install:
    desc: Install Node workspaces (ignores failures if non-node services exist)
    cmds:
      - 'test -f package.json && npm install || true'
  build:
    desc: Build gateway + TS services
    cmds:
      - 'test -f package.json && npm run build || true'
  up:
    desc: docker compose up (detached)
    cmds:
      - 'docker compose up -d --build'
  down:
    desc: docker compose down
    cmds:
      - 'docker compose down'
  health:
    desc: Curl health endpoints (best effort)
    cmds:
      - |
        for port in 8080 8001 8002 8003 8004 8005; do \
          echo "--- $$port"; \
          (curl -s http://localhost:$$port/health || echo 'unreachable') | sed 's/.*/  &/'; \
        done
  new-service:
    desc: "Scaffold a bare service directory (usage: task new-service -- SERVICE=name)"
    cmds:
      - |
        if [ -z "${SERVICE}" ]; then echo 'Set SERVICE: task new-service -- SERVICE=name'; exit 1; fi
        mkdir -p services/${SERVICE}/src
        if [ ! -f services/${SERVICE}/README.md ]; then
          printf '%s\n' "# SERVICE_PLACEHOLDER Service" \
                        "" \
                        "Status: Scaffold only. Implement /health." \
                        "" \
                        "See ../../docs/services/CONVENTIONS.md" \
                        > services/${SERVICE}/README.md
          sed -i '' "s/SERVICE_PLACEHOLDER/${SERVICE}/g" services/${SERVICE}/README.md 2>/dev/null || sed -i "s/SERVICE_PLACEHOLDER/${SERVICE}/g" services/${SERVICE}/README.md
        fi
        echo "Scaffold created at services/${SERVICE}"